# Site settings
baseURL = "https://example.com"
disableHugoGeneratorInject = true
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
languageCode = "en-US"
theme = "hugo-split-theme"
title = "Casper Weiss Bang"

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Casper Weiss Bang"

[params]

# Metadata for search engines and social sharing
author = "Casper Weiss Bang"
description = "Leveraging DDD, CI, and TDD to improve the maintainability of software"
shareImage = "images/social.jpg"
#twitterHandle = "onepagelove"

# Favicon
favicon = "favicon.ico"

# Section - Visual
[params.visual]

# Image
[params.visual.image]
enable = true
file = "images/me.jpg"
position = "center center"

# Links
#
# Links List #1
[[params.links]]
[params.links.list1]
heading = "Connect"

[[params.links.list1.link]]
new_tab = true # Default, open at same tab
text = "Email" 
url = "c@cwb.dk" 

[[params.links.list1.link]]
text = "Linkedin"
url = "https://www.linkedin.com/in/cwbdk/"

# Links List #2
[[params.links]]
[params.links.list2]
heading = "Social"

[[params.links.list2.link]]
text = "Linkedin"
url = "https://www.linkedin.com/in/cwbdk/"

[[params.links.list2.link]]
new_tab = true # new tab
text = "Substack" 
url = "https://cabang.substack.com/" 

## Links List #3
[[params.links]]
[params.links.list3]
heading = "Other"

[[params.links.list3.link]]
text = "Stackoverflow"
url = "https://stackoverflow.com/users/3806354/casper-bang"

[[params.links.list3.link]]
text = "Github"
url = "https://github.com/C0DK/"

[[params.links.list3.link]]
text = "Goodreads"
url = "https://www.goodreads.com/user/show/129022892-casper-weiss-bang"

# The original template is released under the Creative Commons Attribution 3.0 License.
# Please keep the original attribution link when using for your own project.
# If you'd like to use the template without the attribution, you can check out
# the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
for = '/**'
[server.headers.values]
Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
Referrer-Policy = 'strict-origin-when-cross-origin'
X-Content-Type-Options = 'nosniff'
X-Frame-Options = 'DENY'
X-XSS-Protection = '1; mode=block'
