baseURL = "https://www.adrianmoreno.info"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"

# navigation
[menu]

[[menu.header]]
URL = "#about"
name = "About"
weight = 2

[[menu.header]]
URL = "#contact"
name = "Contact"
weight = 4

[params]

sections = ["showcase", "experience", "education", "contact"]

homepageExperienceCount = 4

[params.logo]
text1 = "Casper "
text2 = "Weiss Bang"

[params.footer]
copyright = "© Casper Weiss Bang. Free Hugo theme by Adrián Moreno Peña."
[params.footer.radity_logo]
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"
x = "img/general/design-and-code-radity.png"
