version: "3"

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true
  install:
    desc: installs dependencies
    cmds:
      - npm i -D postcss postcss-cli autoprefixer

  dev:
    desc: Runs dev version of site
    cmd: hugo server -D